logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
server:
  port: 8080
application:
  dataserviceUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservices.staging.fellesdatakatalog.digdir.no}/dataservices
  catalogUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservices.staging.fellesdatakatalog.digdir.no}/catalogs
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://new-harvest-admin:8080}
  harvestAdminApiKey: ${ADMIN_API_KEY}
spring:
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/dataServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
    tags:
      application: fdk-dataservice-harvester
---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/dataServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  dataserviceUri: https://dataservices.staging.fellesdatakatalog.digdir.no/dataservices
  catalogUri: https://dataservices.staging.fellesdatakatalog.digdir.no/catalogs
  harvestAdminRootUrl: https://admin-api.staging.fellesdatakatalog.digdir.no
  harvestAdminApiKey: test-key

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5050/auth/realms/fdk
  rabbitmq:
    host: localhost
    port: 5050
    username: admin
    password: admin
application:
  dataserviceUri: http://localhost:5050/dataservices
  catalogUri: http://localhost:5050/catalogs
  harvestAdminRootUrl: http://localhost:5050
  harvestAdminApiKey: test-key
server.port: 5555
